package views;

import com.toedter.calendar.JDateChooser;

import controllers.EmployeeStatisticsController;
import models.charts.Chart;

import java.awt.Color;
import java.awt.Font;
import java.io.FileOutputStream;
import java.io.PrintStream;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class EmployeeStatisticsView extends javax.swing.JPanel {
	
	static PrintStream ps;
	private EmployeeStatisticsController controller;

	

    public static void show(Exception e) {
        try {
            if (ps == null) {
                ps = new PrintStream(new FileOutputStream("log.txt", true));
            }
            e.printStackTrace(ps);

            int val = JOptionPane.showConfirmDialog(null, e.getMessage() + "!\nXem chi tiểt lỗi?", "Có lỗi xảy ra", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (val == JOptionPane.YES_OPTION) {
                String errorSummary = "";
                int numElement = 0;
                for (StackTraceElement stackTraceElement : e.getStackTrace()) {
                    if (numElement >= 20) {
                        errorSummary += "\t...  more";
                    } else {
                        errorSummary += "\tat " + stackTraceElement;
                        errorSummary += "\n";
                    }
                }
                JOptionPane.showMessageDialog(null, errorSummary, "Có lỗi xảy ra", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {

        }

    }

    DefaultTableModel sessionModel, employeeModel;

    public EmployeeStatisticsView() {
        initComponents();
        
        

        employeeModel = new DefaultTableModel() {
            Class[] types = new Class[]{
                Integer.class, String.class, Integer.class, Integer.class, Integer.class, Integer.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
        sessionModel = new DefaultTableModel() {
            Class[] types = new Class[]{
                Integer.class, String.class, Object.class, Object.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
        tblSession.setModel(sessionModel);
        tblEmployee.setModel(employeeModel);
        sessionModel.addColumn("ID");
        sessionModel.addColumn("Tên nhân viên");
        sessionModel.addColumn("Ngày bắt đầu");
        sessionModel.addColumn("Ngày kết thúc");

        employeeModel.addColumn("ID");
        employeeModel.addColumn("Tên nhân viên");
        employeeModel.addColumn("Lương cơ bản");
        employeeModel.addColumn("Số hóa đơn");
        employeeModel.addColumn("Lương thêm");
        employeeModel.addColumn("Tổng lương");
        setupHeader(tblSession);
        setupHeader(tblEmployee);

        initializeEmployeeStatisticsData();

    }

    private void setupHeader(JTable t) {
        t.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        t.getTableHeader().setBackground(new Color(51, 175, 255));
        t.getTableHeader().setForeground(new Color(255, 255, 255));
        ((DefaultTableCellRenderer) t.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.LEFT);
        t.setAutoCreateRowSorter(true);
    }
    public void addSessionRow(Object[] rowData) {
        sessionModel.addRow(rowData);
    }

    public void addEmployeeRow(Object[] rowData) {
        employeeModel.addRow(rowData);
    }


    public void showError(String message) {
        show(new Exception(message));
    }

    public void showError(Exception e) {
        show(e);
    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public DefaultTableModel getSessionModel() {
        return sessionModel;
    }

    public DefaultTableModel getEmployeeModel() {
        return employeeModel;
    }

    public JDateChooser getDateChooserEnd() {
        return dateChooserEnd;
    }

    public JDateChooser getDateChooserStart() {
        return dateChooserStart;
    }
    
    
    public JPanel getContentPanel() {
        return this; // Trả về toàn bộ giao diện EmployeeStatisticsView
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateChooserStart = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dateChooserEnd = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSession = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1008, 680));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1008, 40));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 40));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 8);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ngày bắt đầu");
        jPanel2.add(jLabel3);

        dateChooserStart.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel2.add(dateChooserStart);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày kết thúc");
        jPanel2.add(jLabel4);

        dateChooserEnd.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel2.add(dateChooserEnd);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel6.setPreferredSize(new java.awt.Dimension(500, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(504, 640));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thống kê phiên làm việc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel1, gridBagConstraints);

        tblSession.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Doanh thu"
            }
        ));
        tblSession.setRowHeight(30);
        jScrollPane1.setViewportView(tblSession);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 407;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jScrollPane1, gridBagConstraints);

        jPanel3.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setPreferredSize(new java.awt.Dimension(504, 640));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Thống kê thông số nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jLabel2, gridBagConstraints);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Doanh thu"
            }
        ));
        tblEmployee.setRowHeight(30);
        jScrollPane2.setViewportView(tblEmployee);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 407;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jScrollPane2, gridBagConstraints);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    private void initializeEmployeeStatisticsData() {
    	// Thêm dòng vào bảng thống kê phiên làm việc
    	addSessionRow(new Object[]{1, "Nguyễn Văn Tú", "11/12/2024 - 9:00", "11/12/2024 - 12:00"});
    	addSessionRow(new Object[]{2, "Chu Văn Nguyên", "11/12/2024 - 12:00", "12/12/2024 - 15:00"});
    	addSessionRow(new Object[]{3, "Trần Doãn Huy", "12/12/2024 - 15:00", "12/12/2024 - 18:00"});
    	addSessionRow(new Object[]{4, "Phan Văn Hương", "12/12/2024 - 17:30", "12/12/2024 - 19:00"});
    	addSessionRow(new Object[]{5, "Nguyễn Thị Tú Uyên", "13/12/2024 - 20:45", "14/12/2024 - 22:00"});


    	// Thêm dòng vào bảng thống kê thông số nhân viên
    	addEmployeeRow(new Object[]{1, "Nguyễn Văn Tú", 5000000, 10, 1000000, 6000000});
    	addEmployeeRow(new Object[]{2, "Chu Văn Nguyên", 8000000, 20, 3000000, 11000000});
    	addEmployeeRow(new Object[]{3, "Trần Doãn Huy", 15000000, 25, 2000000, 17000000});
    	addEmployeeRow(new Object[]{4, "Phan Văn Hương", 30000000, 50, 2000000, 32000000});
    	addEmployeeRow(new Object[]{5, "Nguyễn Thị Tú Uyên", 25000000, 45, 1000000, 26000000});


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChooserEnd;
    private com.toedter.calendar.JDateChooser dateChooserStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblSession;
    // End of variables declaration//GEN-END:variables
}
